name: Build

on:
  pull_request:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore
        run: msbuild WindowsGSM/WindowsGSM.csproj /t:Restore /p:Configuration=Release

      - name: Build
        run: msbuild WindowsGSM/WindowsGSM.csproj /p:Configuration=Release /p:Platform=AnyCPU
